// Shared Restaurant Database
const restaurants = [
    {
        "name": "Heritage Dosa House",
        "city": "Bengaluru",
        "area": "Malleshwaram",
        "cuisine": "South Indian",
        "type": "Quick Bites",
        "rating": 4.8,
        "budget": 1,
        "cost": 300,
        "reviews": "4.8k",
        "image": "images/food_image_9.jpg",
        "verdict": "A legendary South Indian heritage spot famous for its crispy dosas."
    },
    {
        "name": "Saraswat Idli Mess",
        "city": "Bengaluru",
        "area": "Lalbagh",
        "cuisine": "South Indian",
        "type": "Quick Bites",
        "rating": 4.9,
        "budget": 1,
        "cost": 200,
        "reviews": "3.2k",
        "image": "images/food_image_10.jpg",
        "verdict": "Unbeatable soft idlis and traditional filter coffee in Bengaluru."
    },
    {
        "name": "Spice Garden",
        "city": "Bengaluru",
        "area": "Koramangala",
        "cuisine": "Andhra Style",
        "type": "Casual Dining",
        "rating": 4.8,
        "budget": 2,
        "cost": 800,
        "reviews": "8.2k",
        "image": "images/food_image_4.jpg",
        "verdict": "The absolute best choice for fiery Andhra biryanis and spice lovers."
    },
    {
        "name": "Urban Bites",
        "city": "Mumbai",
        "area": "Bandra",
        "cuisine": "North Indian",
        "type": "Casual Dining",
        "rating": 4.5,
        "budget": 2,
        "cost": 950,
        "reviews": "12.5k",
        "image": "images/food_image_3.jpg",
        "verdict": "Vibrant and busy Mughlai dining hotspot with premium grills."
    },
    {
        "name": "Mavalli Cafe",
        "city": "Pune",
        "area": "Deccan Gymkhana",
        "cuisine": "South Indian",
        "type": "Cafe",
        "rating": 4.7,
        "budget": 2,
        "cost": 600,
        "reviews": "2.5k",
        "image": "images/food_image_11.jpg",
        "verdict": "Charming heritage South Indian meal experience in Deccan Gymkhana."
    },
    {
        "name": "The Craft Beer Co.",
        "city": "Pune",
        "area": "Kothrud",
        "cuisine": "Continental",
        "type": "Bar",
        "rating": 4.6,
        "budget": 3,
        "cost": 1500,
        "reviews": "2.7k",
        "image": "images/food_image_12.jpg",
        "verdict": "Top choice in Pune for craft beers, gourmet pizzas, and pub grub."
    },
    {
        "name": "Cafe Aroma Desserts",
        "city": "Pune",
        "area": "Koregaon Park",
        "cuisine": "Desserts",
        "type": "Cafe",
        "rating": 4.9,
        "budget": 1,
        "cost": 500,
        "reviews": "1.8k",
        "image": "images/food_image_13.jpg",
        "verdict": "Delectable ice cream sundae and dessert cafe hotspot in Pune."
    },
    {
        "name": "The Mumbai Tiffin",
        "city": "Mumbai",
        "area": "Dadar",
        "cuisine": "North Indian",
        "type": "Casual Dining",
        "rating": 4.3,
        "budget": 1,
        "cost": 450,
        "reviews": "3.3k",
        "image": "images/food_image_1.jpg",
        "verdict": "A perfect choice for authentic Mumbai-style homecooked meals and budget lunches."
    },
    {
        "name": "The Food Junction",
        "city": "Bengaluru",
        "area": "Jayanagar",
        "cuisine": "Continental",
        "type": "Cafe",
        "rating": 4.5,
        "budget": 2,
        "cost": 1000,
        "reviews": "2.1k",
        "image": "images/food_image_14.jpg",
        "verdict": "A perfect continental cafe hangout spot with gourmet burgers."
    },
    {
        "name": "Vintage Corner Cafe",
        "city": "Mumbai",
        "area": "Colaba",
        "cuisine": "Continental",
        "type": "Cafe",
        "rating": 4.2,
        "budget": 2,
        "cost": 700,
        "reviews": "1.5k",
        "image": "images/food_image_15.jpg",
        "verdict": "Charming British-Indian heritage cafe vibe with premium coffees."
    },
    {
        "name": "Himalayan Kitchen",
        "city": "Bengaluru",
        "area": "Indiranagar",
        "cuisine": "North Indian",
        "type": "Casual Dining",
        "rating": 4.6,
        "budget": 3,
        "cost": 1200,
        "reviews": "3.8k",
        "image": "images/food_image_2.jpg",
        "verdict": "Famous for high-quality North Indian dishes and delectable momos in Indiranagar."
    },
    {
        "name": "Oceanic Coastal Bistro",
        "city": "Mumbai",
        "area": "Juhu",
        "cuisine": "Asian",
        "type": "Fine Dining",
        "rating": 4.7,
        "budget": 4,
        "cost": 2500,
        "reviews": "1.9k",
        "image": "images/food_image_16.jpg",
        "verdict": "Premium fine dining seafood experience by the coast in Mumbai."
    },
    {
        "name": "Taste Hub Vegetarian",
        "city": "Pune",
        "area": "Shivajinagar",
        "cuisine": "South Indian",
        "type": "Casual Dining",
        "rating": 4.1,
        "budget": 1,
        "cost": 400,
        "reviews": "1.1k",
        "image": "images/food_image_16.jpg",
        "verdict": "Excellent value quick service South Indian vegetarian items."
    },
    {
        "name": "Flavor Kitchen Fusion",
        "city": "Bengaluru",
        "area": "UB City",
        "cuisine": "Asian",
        "type": "Fine Dining",
        "rating": 4.4,
        "budget": 4,
        "cost": 2200,
        "reviews": "1.2k",
        "image": "images/food_image_17.jpg",
        "verdict": "High-end molecular gastronomy fusion restaurant in UB City."
    },
    {
        "name": "The Rooftop Lounge",
        "city": "Pune",
        "area": "Kothrud",
        "cuisine": "Global Fusion",
        "type": "Casual Dining",
        "rating": 4.9,
        "budget": 3,
        "cost": 1800,
        "reviews": "1.2k",
        "image": "images/food_image_5.jpg",
        "verdict": "Contemporary global fusion cuisine with Pune's most stunning open-air rooftop sunset views."
    }
];
